### ISSUE TITLE
Prueba 1

### ISSUE THREAD

**Issue by nbxandresvejar** [Arcont01/Ejercicio-Jugador-Ganador#3]
- Las condiciones del calculo no están correctamente implementadas
- Se recomienda el uso de clases y tratamiento de errores
- Puedes usar cualquier framework (o estilo) que consideres
- Hacer uso de pruebas unitarias

**Comment by Arcont01** [comment]
Hola tengo varias dudas y puntos que pues nunca me aclararon.

1.  Cuanto tiempo tengo para corregir errores.
2. Al usar un framework es posible entonces cambiar todo lo ya hecho?.
3. No se que condiciones del calculo se deberían implementar ya que eso no viene descrito en la prueba.

**Comment by nbxandresvejar** [comment]
1. tomate la libertad de implementar lo que mejor domines-
2. Claro, esto es tu solución, expresa en el código lo que sabes
3. Este es un tema de entendimiento del problema, en el caso del problema 2 la forma de obtener el resultado no es correcta, al ser un challenge de síntesis no puedo darte más detalles. 
Saludos

**Comment by Arcont01** [comment]
Se implementa lumen con clases y pruebas unitarias y se agregan mas condiciones
