### ISSUE TITLE
Prueba 2

### ISSUE THREAD

**Issue by nbxandresvejar** [Arcont01/Ejercicio-Jugador-Ganador#4]
Las condiciones del calculo no están correctamente implementadas
Se recomienda el uso de clases y tratamiento de errores

**Comment by Arcont01** [comment]
Se estan usando clases y se comprueban posibles errores

**Comment by Arcont01** [comment]
Es posible que me des mas detalles de a que te refieres a usar clases ya que se estan implementando

**Comment by nbxandresvejar** [comment]
Si tienes razón, :), sin embargo revisa a detalle el tratamiento de errores.

Saludos

**Comment by Arcont01** [comment]
Se comprueban posibles errores así y se guarda un log si llegara a pasar un error inesperado, así como también se hace un cambio en el calculo de diferencias
